name: Image push for master
on: 
  push:
    branches:
      - master
env:
  image-push-owner: 'dougbtv'
jobs:
  push-amd64:
    name: Image push/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.repository_owner == ${{ env.image-push-owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push container image
        if: github.repository_owner == ${{ env.image-push-owner }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dougbtv/whereabouts:latest
          file: deployments/Dockerfile

  push-origin:
    name: Image push/origin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.repository_owner == ${{ env.image-push-owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push container image
        if: github.repository_owner == ${{ env.image-push-owner }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dougbtv/whereabouts-ocp:latest
          file: deployments/Dockerfile.openshift
